In [33]:
from time import sleep

import yfinance as yf
import pandas as pd
import requests

data = pd.read_excel("/upgrade/AI/projects/data/stock_investment.xlsx")
data

,Account,Company,Shares,Avg Price (₹),Invested Value (₹),Market Cap,Sector,NSE Symbol,BSE Symbol
0,Rupa,Vedanta,130,448.50,58305.00,Large,mining & mineral products,VEDL,500295
1,Rupa,Hindustan Zinc,120,442.04,53044.80,Large,non ferrous metals,HINDZINC,500188
2,Rupa,Coal India,110,390.72,42979.20,Large,mining & mineral products,COALINDIA,533278
3,Rupa,Rail Vikas Nigam,76,385.15,29271.40,Mid,infrastructure developers & operators,RVNL,533185
4,Rupa,HPCL,50,418.95,20947.50,Mid,refineries,HPCL,500547
5,Rupa,Power Grid Corp,30,290.32,8709.60,Large,others,POWERGRID,533155
6,Rupa,Power Finance Corp,20,411.70,8234.00,Large,others,PFC,532827
7,Rupa,IOCL,50,143.28,7164.00,Large,refineries,IOC,530965
8,Rupa,IRFC,50,139.20,6960.00,Large,others,IRFC,532921
9,Rupa,ONGC,20,237.80,4756.00,Large,others,ONGC,500312
10,Rupa,Capital Infra,50,77.85,3892.50,Small,others,CAPITALINFRA,532968
11,Rupa,IRBINVIT,50,54.74,2737.00,Small,others,IRBINVIT,540526
12,Rupa,RattanIndia Power,210,13.23,2778.30,Small,others,RATTANIND,532996
13,Rupa,Vodafone Idea,225,7.17,1613.25,Mid,others,IDEA,532822
14,Brijesh,HPCL,30,402.38,12071.40,Mid,refineries,HPCL,500547
15,Brijesh,NTPC Green Energy,100,122.88,12288.00,Mid,power generation and distribution,NTPCGREEN,544289
16,Brijesh,Urja Global,700,22.83,15981.00,Small,automobile,URJA,526987
17,Brijesh,Coal India,20,396.40,7928.00,Large,mining & mineral products,COALINDIA,533278
18,Brijesh,Hindustan Zinc,10,414.45,4144.50,Large,non ferrous metals,HINDZINC,500188
19,Brijesh,Mishtann Foods,600,7.72,4632.00,Small,others,MISHTANN,539594
20,Brijesh,Rail Vikas Nigam,10,338.30,3383.00,Mid,infrastructure developers & operators,RVNL,533185
21,Brijesh,Vedanta,5,429.00,2145.00,Large,mining & mineral products,VEDL,500295
22,Brijesh,GTL Infrastructure,1200,2.32,2784.00,Small,others,GTLINFRA,532745
23,Brijesh,ICICI Prud Nifty 100 ETF,52,29.48,1532.96,Large,others,ICICINIFTY,-
24,Brijesh,Orient Green Power,100,21.12,2112.00,Small,power generation and distribution,ORIENTGREEN,532911
25,Brijesh,Jindal Worldwide,10,54.70,547.00,Small,others,JINDWORLD,531543
26,Brijesh,Seven Hill Indus,47,0.95,44.65,Small,others,SEVENHILL,511760

In [34]:
# What is the total number of company records in the dataset?
total_companies = data["Company"].count()
total_companies

np.int64(27)

In [35]:
# How many companies has each account invested in?
data.groupby("Account")["Company"].count()

Account
Brijesh    13
Rupa       14
Name: Company, dtype: int64

In [36]:
# What is the total invested value for each account?
data.groupby("Account")["Invested Value (₹)"].sum()

Account
Brijesh     69593.51
Rupa       251392.55
Name: Invested Value (₹), dtype: float64

In [37]:
# Calculate the sum of all investments in the stock-market.
total_invested_value = data["Invested Value (₹)"].sum()
total_invested_value

np.float64(320986.06000000006)

In [38]:
# What is the total number of shares and total invested value for each company?
company_summary = data.groupby("Company").agg({
    'Shares': 'sum',
    'Invested Value (₹)': 'sum'
}).reset_index()
company_summary.sort_values("Invested Value (₹)", ascending=False)

                     Company  Shares  Invested Value (₹)
20                   Vedanta     135            60450.00
4             Hindustan Zinc     130            57189.30
1                 Coal India     130            50907.20
3                       HPCL      80            33018.90
16          Rail Vikas Nigam      86            32654.40
19               Urja Global     700            15981.00
11         NTPC Green Energy     100            12288.00
15           Power Grid Corp      30             8709.60
14        Power Finance Corp      20             8234.00
6                       IOCL      50             7164.00
8                       IRFC      50             6960.00
12                      ONGC      20             4756.00
10            Mishtann Foods     600             4632.00
0              Capital Infra      50             3892.50
2         GTL Infrastructure    1200             2784.00
17         RattanIndia Power     210             2778.30
7                   IRBINVIT      50             2737.00
13        Orient Green Power     100             2112.00
21             Vodafone Idea     225             1613.25
5   ICICI Prud Nifty 100 ETF      52             1532.96
9           Jindal Worldwide      10              547.00
18          Seven Hill Indus      47               44.65

In [39]:
# Total invested value per Market Cap
marketcap_sum = data.groupby("Market Cap")["Invested Value (₹)"].sum()
# print("marketcap_sum: ", marketcap_sum)

# Total invested value overall
total_invested_marketcap_wise = marketcap_sum.sum()
# print("total_invested: ", total_invested)

# Percentage per Market Cap
marketcap_percentage = (marketcap_sum / total_invested_marketcap_wise) * 100
# print("marketcap_percentage: ", marketcap_percentage)

# Convert to DataFrame
marketcap_percentage = marketcap_percentage.reset_index(name='Percentage (%)')

print(marketcap_percentage)

  Market Cap  Percentage (%)
0      Large       64.147041
1        Mid       24.790656
2      Small       11.062303

In [40]:
# Total invested value per Sector
sector_sum = data.groupby("Sector")["Invested Value (₹)"].sum()
sector_sum

total_invested_sector_wise = sector_sum.sum()
total_invested_sector_wise

sector_percentage = (sector_sum / total_invested_sector_wise) * 100
sector_percentage

sector_percentage = sector_percentage.reset_index(name="Percentage (%)").sort_values("Percentage (%)", ascending=False)
sector_percentage

                                  Sector  Percentage (%)
2              mining & mineral products       34.692223
3                     non ferrous metals       17.816755
4                                 others       15.334392
6                             refineries       12.518581
1  infrastructure developers & operators       10.173152
0                             automobile        4.978721
5      power generation and distribution        4.486176

In [50]:
# Convert symbols to list
NSE_symbols = data["NSE Symbol"].tolist()

# Dictionary to store current prices
current_prices = {}

for company, symbol in zip(data['Company'], NSE_symbols):
    try:
        yf_symbol = f"{symbol}.NS"  # Use .BO for BSE, .NS for NSE
        stock = yf.Ticker(yf_symbol)
        price = stock.info.get('regularMarketPrice', None)  # Use .get() to avoid KeyError
        if price is None:
            print(f"Price not found for {company} ({symbol})")
            pass
        else:
            current_prices[company] = price
            print(f"{company}: ₹{price}")
            pass
    except Exception as e:
        print(f"Error fetching {company} ({symbol}): {e}")
        pass

# Optional: Add current price to DataFrame
data['Current Price (₹)'] = data['Company'].map(current_prices)

Vedanta: ₹445.5
Hindustan Zinc: ₹430.0
Coal India: ₹384.7
Rail Vikas Nigam: ₹330.8
Price not found for HPCL (HPCL)
Power Grid Corp: ₹288.4
Power Finance Corp: ₹403.4
IOCL: ₹141.44
IRFC: ₹126.73
ONGC: ₹237.93

HTTP Error 404:

Price not found for Capital Infra (CAPITALINFRA)
IRBINVIT: ₹66.38

HTTP Error 404:

Price not found for RattanIndia Power (RATTANIND)
Vodafone Idea: ₹6.79
Price not found for HPCL (HPCL)
NTPC Green Energy: ₹105.18
Urja Global: ₹13.94
Coal India: ₹384.7
Hindustan Zinc: ₹430.0

HTTP Error 404:

Price not found for Mishtann Foods (MISHTANN)
Rail Vikas Nigam: ₹330.8
Vedanta: ₹445.5
GTL Infrastructure: ₹1.53
Price not found for ICICI Prud Nifty 100 ETF (ICICINIFTY)

HTTP Error 404:

Price not found for Orient Green Power (ORIENTGREEN)
Jindal Worldwide: ₹36.68

HTTP Error 404:

Price not found for Seven Hill Indus (SEVENHILL)

In [48]:
# Calculate Profit/Loss
data['Profit/Loss (₹)'] = (data['Current Price (₹)'] * data['Shares']) - data['Invested Value (₹)']

# Print only selected columns
pd.set_option('display.width', 1000)        # Set wide enough width
pd.set_option('display.max_columns', None)  # Show all columns

print(data[["Company", "Shares", "Avg Price (₹)", "Current Price (₹)", "Invested Value (₹)", "Profit/Loss (₹)"]])

                     Company  Shares  Avg Price (₹)  Current Price (₹)  Invested Value (₹)  Profit/Loss (₹)
0                    Vedanta     130         448.50             445.45            58305.00          -396.50
1             Hindustan Zinc     120         442.04             429.90            53044.80         -1456.80
2                 Coal India     110         390.72             384.80            42979.20          -651.20
3           Rail Vikas Nigam      76         385.15             330.85            29271.40         -4126.80
4                       HPCL      50         418.95                NaN            20947.50              NaN
5            Power Grid Corp      30         290.32             288.35             8709.60           -59.10
6         Power Finance Corp      20         411.70             403.45             8234.00          -165.00
7                       IOCL      50         143.28             141.45             7164.00           -91.50
8                       IRFC      50         139.20             126.75             6960.00          -622.50
9                       ONGC      20         237.80             237.95             4756.00             3.00
10             Capital Infra      50          77.85                NaN             3892.50              NaN
11                  IRBINVIT      50          54.74              63.27             2737.00           426.50
12         RattanIndia Power     210          13.23                NaN             2778.30              NaN
13             Vodafone Idea     225           7.17               6.79             1613.25           -85.50
14                      HPCL      30         402.38                NaN            12071.40              NaN
15         NTPC Green Energy     100         122.88             105.15            12288.00         -1773.00
16               Urja Global     700          22.83              13.94            15981.00         -6223.00
17                Coal India      20         396.40             384.80             7928.00          -232.00
18            Hindustan Zinc      10         414.45             429.90             4144.50           154.50
19            Mishtann Foods     600           7.72               6.10             4632.00          -972.00
20          Rail Vikas Nigam      10         338.30             330.85             3383.00           -74.50
21                   Vedanta       5         429.00             445.45             2145.00            82.25
22        GTL Infrastructure    1200           2.32               1.54             2784.00          -936.00
23  ICICI Prud Nifty 100 ETF      52          29.48                NaN             1532.96              NaN
24        Orient Green Power     100          21.12                NaN             2112.00              NaN
25          Jindal Worldwide      10          54.70              36.74              547.00          -179.60
26          Seven Hill Indus      47           0.95               0.52               44.65           -20.21